export const Ingredients = {
  GET_ALL_INGREDIENTS: 'GET_ALL_INGREDIENTS',
  ADD_ONE_INGREDIENT: 'ADD_ONE_INGREDIENT',
  UPDATE_ONE_INGREDIENT: 'UPDATE_ONE_INGREDIENT',
  DELETE_ONE_INGREDIENT: 'DELETE_ONE_INGREDIENT'
};

export const Recipes = {
  GET_ALL_RECIPES: 'GET_ALL_RECIPES',
  ADD_ONE_RECIPE: 'ADD_ONE_RECIPE',
  UPDATE_ONE_RECIPE: 'UPDATE_ONE_RECIPE',
  DELETE_ONE_RECIPE: 'DELETE_ONE_RECIPE'
}