export const Ingredients = {
  GET_ALL_INGREDIENTS: 'GET_ALL_INGREDIENTS',
  ADD_ONE_INGREDIENT: 'ADD_ONE_INGREDIENT',
  UPDATE_ONE_INGREDIENT: 'UPDATE_ONE_INGREDIENT',
  DELETE_ONE_INGREDIENT: 'DELETE_ONE_INGREDIENT'
};